import os
import argparse
import time
import yaml
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader

# Import our newly unified dataset
from src.data.jsl_dataset import MultiVideoFaceMouthSequenceDataset

# Import colleague's localization modules
from src.models.localization.mouth_landmarks import (
    prepare_data, 
    normalize_window_length, 
    RFMouthLandmarkDetector, 
    LRMouthLandmarkDetector, 
    CLASS_ENCODER_SIMPLE
)
from src.models.localization.utils import (
    MouthMovementEvaluator, 
    MouthGraphDataset, 
    GCNMouthMovementDetector, 
    collate_graph_windows,
    prediction_to_elan
)

def load_data(data_dir, num_classes, class_encoder, downsample, classifier, shuffle=True, annotation_end_info=None):
    """Loads the LOCALIZATION ground truth generated by our EAF processor."""
    data = MultiVideoFaceMouthSequenceDataset(
        root_dir=data_dir,
        task='localization',         # <--- Crucial: Uses the Union Ground Truth
        mode='no_img',               # <--- Crucial: Loads only landmarks for speed
        return_landmarks=True,
        transform=None,
        min_seq_len=11,
        max_seq_len=30,
        downsample=downsample,
        label_mapping=class_encoder,
        annotation_end_info=annotation_end_info
    )

    # Colleague's normalizer
    norm_samples = normalize_window_length(
        data.samples, 
        sequence_keys=['landmarks_mouth_inner', 'landmarks_cheeks'], 
        target_length=12
    )

    # Filter out ignored classes
    relevant_samples = [s for s in norm_samples if class_encoder.get(s['label'], -1) != -1]

    if classifier in ["rf", "lr"]:
        frames, gt_class, segment_keys = prepare_data(relevant_samples, inner_mouth=True, num_classes=num_classes)
        return frames, gt_class, segment_keys
    elif classifier == "gcn":
        dataset = MouthGraphDataset(relevant_samples, label_encoder=class_encoder, shuffle=shuffle)
        return dataset
    else:
        raise NotImplementedError

def main():
    parser = argparse.ArgumentParser(description="Train Localization Model")
    parser.add_argument("--data_train", type=str, required=True, help="Path to processed train JSONs")
    parser.add_argument("--data_test", type=str, required=True, help="Path to processed test JSONs")
    parser.add_argument("--elan_base", type=str, required=True, help="Path to raw ELAN folder for saving predictions")
    parser.add_argument("--save_dir", type=str, default="./predictions", help="Directory to save models/JSONs")
    parser.add_argument("--classifier", type=str, choices=["gcn", "rf", "lr"], default="gcn")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--downsample", type=int, default=1, help="0=None, 1=Partial, 2=Full")
    parser.add_argument("--ann_info", type=str, default=None, help="Path to annotation_ends.yaml (Optional)")
    parser.add_argument("--model_path", type=str, default=None, help="Path to load pretrained model (Optional)")
    args = parser.parse_args()

    os.makedirs(args.save_dir, exist_ok=True)
    num_classes = -1
    
    # Load Metadata (If provided)
    ann_info = None
    if args.ann_info and os.path.exists(args.ann_info):
        with open(args.ann_info, 'r') as f:
            ann_info = yaml.safe_load(f)

    print(f"--- Running {args.classifier.upper()} Localization Pipeline ---")

    # ---------------------------------------------------------
    # RANDOM FOREST & LOGISTIC REGRESSION
    # ---------------------------------------------------------
    if args.classifier in ["rf", "lr"]:
        if args.data_train == args.data_test:
            # Auto-split if train and test point to the same directory
            X_all, y_all, keys_all = load_data(args.data_train, num_classes, CLASS_ENCODER_SIMPLE, args.downsample, args.classifier, annotation_end_info=ann_info)
            X_train, X_test, y_train, y_test, train_keys, test_keys = train_test_split(X_all, y_all, keys_all, test_size=0.2, random_state=42, stratify=y_all)
        else:
            X_train, y_train, train_keys = load_data(args.data_train, num_classes, CLASS_ENCODER_SIMPLE, args.downsample, args.classifier, annotation_end_info=ann_info)
            X_test, y_test, test_keys = load_data(args.data_test, num_classes, CLASS_ENCODER_SIMPLE, args.downsample, args.classifier, annotation_end_info=ann_info)
            
        model = RFMouthLandmarkDetector() if args.classifier == "rf" else LRMouthLandmarkDetector()
        
        print(f"Training on {len(X_train)} samples...")
        model.train(X_train, y_train)
        
        y_pred, y_pred_proba = model.predict(X_test)
        
        # Predict & Save ELAN info
        save_path = os.path.join(args.save_dir, time.strftime("%Y%m%d-%H%M%S") + f"_{args.classifier}_predictions.json")
        labels_dict = model.predict_boundaries(X_test, test_keys, CLASS_ENCODER_SIMPLE, save_path=save_path, elan_folder=args.elan_base)
        
        print("\n--- Evaluation Metrics ---")
        evaluator = MouthMovementEvaluator(y_test, y_pred, y_pred_proba, test_keys)
        evaluator.evaluate()

    # ---------------------------------------------------------
    # GRAPH CONVOLUTIONAL NETWORK (GCN)
    # ---------------------------------------------------------
    elif args.classifier == "gcn":
        train_data = load_data(args.data_train, num_classes, CLASS_ENCODER_SIMPLE, args.downsample, "gcn", annotation_end_info=ann_info) if not args.model_path else None
        test_data = load_data(args.data_test, num_classes, CLASS_ENCODER_SIMPLE, args.downsample, "gcn", shuffle=False, annotation_end_info=ann_info)
        
        model = GCNMouthMovementDetector(in_channels=2, batching=True, model_path=args.model_path)
        
        train_loader = DataLoader(train_data, batch_size=64, shuffle=True, collate_fn=collate_graph_windows) if train_data else None
        test_loader = DataLoader(test_data, batch_size=64, shuffle=False, collate_fn=collate_graph_windows)
        
        if not args.model_path:
            print(f"Training GCN on {len(train_data)} samples for {args.epochs} epochs...")
            model.train(train_loader, test_loader, epochs=args.epochs)
            model.save_model(os.path.join(args.save_dir, time.strftime("%Y%m%d-%H%M%S") + "_gcn_model.pt"))
            
        print("\nGenerating Predictions & Boundaries...")
        save_path = os.path.join(args.save_dir, time.strftime("%Y%m%d-%H%M%S") + "_gcn_predictions.json")
        model.predict_boundaries(test_loader, CLASS_ENCODER_SIMPLE, save_path=save_path, elan_folder=args.elan_base)

if __name__ == '__main__':
    main()